platformsh/template-builder

drupal7-vanilla/Makefile
drupal7-vanilla/allow-settings-files.patch
drupal7-vanilla/files/.platform.app.yaml
drupal7-vanilla/files/.platform/routes.yaml
drupal7-vanilla/files/.platform/services.yaml
drupal7-vanilla/files/README.md
drupal7-vanilla/files/docroot/drushrc.php
drupal7-vanilla/files/docroot/sites/default/settings.php
drupal7-vanilla/files/docroot/sites/default/settings.platformsh.php

Because people have been asking for it.

Drupal7 vanilla

---

.gitignore
dodo.py

As discussed with Adam M in Barcelona.

Rename the template directory to build, to avoid namespace collissions.

---

dodo.py

Resolves https://github.com/platformsh/template-wordpress/pull/12

Fix wordpress installer-path structure issues.

---

dodo.py

Because some are compatible only with one or the other.

Support branches or tags for upstream sources

---

Pipfile
Pipfile.lock

Ran automated script. Got this.

uUpdate django

---

templates/drupal8/files/.platform.app.yaml

Resolves https://github.com/platformsh/template-drupal8/pull/31

Update Drupal 8 to recommended deploy practices.

---

templates/drupal8/files/.platform.app.yaml
templates/drupal8/files/drush/platformsh_generate_drush_yml.php
templates/govcms8/files/.platform.app.yaml
templates/govcms8/files/drush/platformsh_generate_drush_yml.php

Resolves https://github.com/platformsh/template-drupal8/pull/26

Reference PHP scripts for Drush in a way that doesn't care about the execute bit.

---

project/drupal.py
templates/drupal8/files/web/sites/default/settings.platformsh.php

This is built off of the autotag branch to reduce the chances of conflicts, which may or may not be the best decision but meh...
Ready for review.  Don't merge until autotag is in, of course.

Use Config Reader for Drupal 8

---

project/drupal.py
templates/drupal8/files/.platform.app.yaml
templates/drupal8/files/.platform/services.yaml
templates/drupal8/files/web/sites/default/settings.platformsh.php

This makes it a one liner to enable.

Ship Drupal with Redis ready but not enabled.

---

templates/django1/files/.platform.template.yaml
templates/django2/files/.platform.template.yaml
templates/drupal7/files/.platform.template.yaml
templates/drupal7_vanilla/files/.platform.template.yaml
templates/drupal8/files/.platform.template.yaml
templates/flask/files/.platform.template.yaml
templates/golang/files/.platform.template.yaml
templates/govcms8/files/.platform.template.yaml
templates/laravel/files/.platform.template.yaml
templates/magento2ce/files/.platform.template.yaml
templates/php/files/.platform.template.yaml
templates/python2/files/.platform.template.yaml
templates/python3/files/.platform.template.yaml
templates/python3_uwsgi/files/.platform.template.yaml
templates/symfony3/files/.platform.template.yaml
templates/symfony4/files/.platform.template.yaml
templates/wordpress/files/.platform.template.yaml

Fix typo across all template files.

---

templates/django1/files/Pipfile
templates/django1/files/Pipfile.lock
templates/django2/files/Pipfile
templates/django2/files/Pipfile.lock

See 
https://github.com/platformsh/template-django2/pull/6
https://github.com/platformsh/template-django1/pull/3

Update Django baselines to require the latest security fix.

---

project/drupal.py
templates/drupal7/files/project.make

Another day, another security release.

Update Drupal 7

---

templates/flask/files/.platform.app.yaml
templates/flask/files/.platform.template.yaml
templates/flask/files/.platform/services.yaml
templates/flask/files/Pipfile
templates/flask/files/Pipfile.lock
templates/flask/files/requirements.txt
templates/flask/files/server.py
templates/pyramid/files/.platform.template.yaml
templates/python2/files/README.md
templates/python3/files/.platform.app.yaml
templates/python3/files/.platform/services.yaml
templates/python3/files/Pipfile
templates/python3/files/Pipfile.lock
templates/python3/files/README.md
templates/python3/files/server.py

Small Readme change to Python 2. Add config-reader to Python3 and Flask

Add Config-reader

---

README.md

While giving Bob the tour I realized the README was a bit out of date.  So, updating it.

Update README file for more recent changes to the commands.

---

templates/flask/files/server.py
templates/pyramid/files/app.py
templates/python2/files/server.py
templates/python3/files/server.py
templates/python3_uwsgi/files/app.py

Otherwise tethered dev over a tunnel fails.

Explicitly specify the port from the connection in Flask

---

templates/symfony3/files/.platform.app.yaml
templates/symfony4/files/.platform.app.yaml

See:
https://github.com/platformsh/template-symfony4/pull/20
https://github.com/platformsh/template-symfony3/pull/14

Update Symonfy examples to use PHP 7.3.

---

templates/python3_uwsgi/files/.platform.template.yaml

See also: https://github.com/platformsh/template-python3-uwsgi/pull/6

Udpate template profile to Python from copy-pasta PHP.

---

templates/magento2ce/platformsh.patch

Some line numbers moved around.

Reroll Magento patch file

---

templates/magento2ce/files/.platform.template.yaml

Bump PHP version in Magento template definition file.

---

templates/django2/files/myapp/settings.py

Reverts platformsh/template-builder#77

Revert "Don't set a default secret key, even for local use."

---

templates/django2/files/Pipfile
templates/wagtail/files/Pipfile

https://github.com/platformsh/template-builder/network/alert/templates/django2/files/Pipfile.lock/django/open

upgrade django

---

templates/django1/files/Pipfile
templates/django1/files/Pipfile.lock
templates/django1/files/requirements.txt
templates/django2/files/Pipfile.lock

https://github.com/platformsh/template-builder/network/alert/templates/django2/files/Pipfile.lock/django/open
https://github.com/platformsh/template-builder/network/alert/templates/django1/files/requirements.txt/django/open
https://github.com/platformsh/template-builder/network/alert/templates/django1/files/Pipfile.lock/django/open

more django security updates

---

templates/golang/files/README.md

https://github.com/platformsh/template-golang/pull/7

Update README with config-reader link.

---

templates/spring-boot-maven-mysql/files/.platform/services.yaml

https://github.com/platformsh/template-spring-boot-maven-mysql/pull/4

updates the spring service to use MySQL instead of MariaDB

---

templates/laravel/files/.platform.app.yaml
templates/laravel/files/.platform.template.yaml

Adding the changes from here: https://github.com/platformsh/template-laravel/pull/21
To the template builder

Adding recent template-laravel changes to template-builder

---

templates/gin/files/README.md

https://github.com/platformsh/template-gin/pull/3

Fixes Gin title.

---

templates/lisp/.platform.template.yaml
templates/lisp/files/.editorconfig
templates/lisp/files/.platform.app.yaml
templates/lisp/files/.platform/routes.yaml
templates/lisp/files/.platform/services.yaml
templates/lisp/files/README.md
templates/lisp/files/example.asd
templates/lisp/files/example.lisp

https://github.com/platformsh/template-lisp/pull/1

Initial Lisp template

---

templates/flask/files/Pipfile
templates/flask/files/Pipfile.lock
templates/python3/files/Pipfile
templates/python3/files/Pipfile.lock

Fixes https://github.com/platformsh/template-builder/network/alert/templates/python3/files/Pipfile.lock/werkzeug/open and https://github.com/platformsh/template-builder/network/alert/templates/flask/files/Pipfile.lock/werkzeug/open

Werkzeug security fixes for python3 and flask

---

templates/beego/files/.platform.app.yaml
templates/echo/files/.platform.app.yaml
templates/gin/files/.platform.app.yaml
templates/golang/files/.platform.app.yaml
templates/hugo/files/.platform.app.yaml

cf: 
https://github.com/platformsh/template-beego/pull/4
https://github.com/platformsh/template-echo/pull/3
https://github.com/platformsh/template-gin/pull/4
https://github.com/platformsh/template-golang/pull/9
https://github.com/platformsh/template-hugo/pull/5

Update all Go repos to use 1.13.

---

templates/drupal8multi/files/README.md
templates/drupal8multi/files/psh-subsite-add.php

cf: https://github.com/platformsh/template-drupal8multi/pull/4

Automation script for multisite creation

---

templates/drupal8/files/web/sites/default/settings.platformsh.php

This should also be applied to the Drupal 7 repos before we commit.

Remove host filtering in Drupal, as Platform.sh already does it. 

---

project/remote.py
templates/drupal8-govcms8/files/drush/platformsh_drush.inc
templates/drupal8-multisite/files/drush/platformsh_drush.inc
templates/drupal8-opigno/files/drush/platformsh_drush.inc
templates/drupal8/files/drush/platformsh_drush.inc

cf:
https://github.com/platformsh-templates/drupal8/pull/2
https://github.com/platformsh-templates/drupal8-multisite/pull/2
https://github.com/platformsh-templates/drupal8-opigno/pull/2
https://github.com/platformsh-templates/drupal8-govcms8/pull/2

Fix bugs in Drush glue code.

---

templates/spring-boot-gradle-mysql/files/.platform.app.yaml
templates/spring-boot-maven-mysql/files/.platform.app.yaml
templates/spring-mvc-maven-mongodb/files/.platform.app.yaml

* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/2
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/2
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/2

defines maximum memory to Spring application.

---

project/__init__.py
project/akeneo.py
project/drupal.py
project/remote.py
project/wordpress.py

Just some code simplification to centralize composer editing.

Composer cleanup

---

templates/spring-kotlin/files/src/main/kotlin/sh/platform/template/spring/kotlin/CityController.kt

https://github.com/platformsh-templates/spring-kotlin/pull/2

Renames controller class name

---

templates/magento2ce/files/.platform/routes.yaml

cf: https://github.com/platformsh-templates/magento2ce/pull/2

Fix route app name.

---

templates/micronaut/files/pom.xml
templates/microprofile-helidon/files/pom.xml
templates/microprofile-kumuluzee/files/pom.xml
templates/microprofile-openliberty/files/pom.xml
templates/microprofile-payara/files/pom.xml
templates/microprofile-thorntail/files/pom.xml
templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml

* https://github.com/platformsh-templates/microprofile-payara/pull/2
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/2
* https://github.com/platformsh-templates/microprofile-openliberty/pull/2
* https://github.com/platformsh-templates/microprofile-helidon/pull/2
* https://github.com/platformsh-templates/microprofile-thorntail/pull/2
* https://github.com/platformsh-templates/micronaut/pull/2
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/4
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/4
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/4
* https://github.com/platformsh-templates/spring-kotlin/pull/3

Updates platform.sh Config Reader library

---

templates/microprofile-openliberty/files/pom.xml

Link: https://github.com/platformsh-templates/microprofile-openliberty/pull/3

Updates open liberty plugin

---

templates/jetty/files/pom.xml

https://github.com/platformsh-templates/jetty/pull/2

updates Platform.sh libraty at Jetty

---

project/symfony.py

cf: https://github.com/platformsh-templates/symfony3/pull/2

Fix Monolog dependency issue in Symfony 3.

---

dodo.py
project/symfony.py
templates/symfony5/.platform.template.yaml
templates/symfony5/files/.platform.app.yaml
templates/symfony5/files/.platform/routes.yaml
templates/symfony5/files/.platform/services.yaml
templates/symfony5/files/README.md

cf: https://github.com/platformsh-templates/symfony5/pull/1

Add Symfony 5 template.

---

project/pimcore.py

cf: https://github.com/platformsh-templates/pimcore/pull/2

Be more forgiving in the composer command for Pimcore

---

templates/microprofile-payara/files/pom.xml

https://github.com/platformsh-templates/microprofile-payara/pull/4

Updates payara to version 5.194

---

project/drupal.py
project/remote.py
templates/drupal8-multisite/.platform.template.yaml
templates/drupal8-multisite/files/README.md
templates/drupal8/.platform.template.yaml
templates/drupal8/files/README.md

Drupal has finally gotten with the 2010s...
cf: 
https://github.com/platformsh-templates/drupal8/pull/4
https://github.com/platformsh-templates/drupal8-multisite/pull/4

Use Drupal 8.8 and the "Recommended" Composer version now

---

templates/microprofile-helidon/files/pom.xml

* https://github.com/platformsh-templates/microprofile-helidon/pull/4

Updates Helidon to version 1.4.1

---

templates/microprofile-thorntail/files/pom.xml

https://github.com/platformsh-templates/microprofile-thorntail/pull/4

updates thorntail version

---

project/backdrop.py

Fixes https://github.com/platformsh/template-builder/issues/182

Update Backdrop CMS to 1.14.2

---

templates/wordpress/files/wp-config.php

cf: https://github.com/platformsh-templates/wordpress/pull/6

Be more forgiving in the platform check for Wordpress.

---

templates/microprofile-payara/files/pom.xml
templates/microprofile-payara/files/src/main/webapp/WEB-INF/web.xml
templates/microprofile-payara/files/src/test/java/sh/platform/template/AppTest.java
templates/microprofile-payara/files/src/test/resources/META-INF/beans.xml

Ref: https://github.com/platformsh-templates/microprofile-payara/pull/5

Payara updates

---

templates/magento2ce/files/README.md

No matching template PR yet, build giving me troubles for some reason.

Fixes link to patch file in README.

---

templates/django2/files/Pipfile
templates/django2/files/Pipfile.lock

cf: https://github.com/platformsh-templates/django2/pull/5

Update Django2 to 2.2.8.

---

templates/django1/files/Pipfile
templates/django1/files/Pipfile.lock

cf: https://github.com/platformsh-templates/django1/pull/4

Update Django 1 for security updates.

---

templates/jetty/files/pom.xml
templates/jetty/files/src/test/java/sh/platform/template/AppTest.java
templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-gradle-mysql/files/src/test/java/sh/platform/template/AppTest.java
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-boot-maven-mysql/files/src/test/java/sh/platform/template/AppTest.java
templates/spring-kotlin/files/pom.xml
templates/spring-kotlin/files/src/test/java/sh/platform/template/AppTest.java
templates/spring-mvc-maven-mongodb/files/pom.xml
templates/spring-mvc-maven-mongodb/files/src/test/java/sh/platform/template/AppTest.java

This PR has the goal of updating Spring version Therefore, it will remove deprecated annotations and create a test context and update the JUnit to JUnit Jupiter 5.6.0.
* https://github.com/platformsh-templates/spring-kotlin/pull/5
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/6
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/6
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/6
* https://github.com/platformsh-templates/jetty/pull/4
* https://github.com/platformsh/template-builder/pull/193

Update Spring versions and create test scope

---

project/remote.py
templates/magento2ce/files/.magento.env.yaml
templates/magento2ce/files/.platform.app.yaml
templates/magento2ce/files/README.md
templates/magento2ce/files/deploy
templates/magento2ce/files/disable-cron-workers.php

* Disable the working directory wipe command.
* Disable worker-spawning from cron.
* Document things.
cf: https://github.com/platformsh-templates/magento2ce/pull/7

Magento fixes

---

templates/jetty/files/.platform.app.yaml
templates/jetty/files/src/main/webapp/WEB-INF/web.xml
templates/microprofile-payara/files/pom.xml
templates/microprofile-payara/files/src/main/webapp/WEB-INF/web.xml
templates/spring-kotlin/files/src/main/webapp/WEB-INF/web.xml

* https://github.com/platformsh-templates/jetty/pull/5
* https://github.com/platformsh-templates/microprofile-payara/pull/7
* https://github.com/platformsh-templates/spring-kotlin/pull/6

upgrade web.xml to version 4.0

---

templates/drupal8-multisite/files/web/sites/default/settings.php
templates/drupal8-multisite/files/web/sites/first/settings.php
templates/drupal8-multisite/files/web/sites/second/settings.php
templates/drupal8-multisite/files/web/sites/settings.platformsh.php

Replicated from https://github.com/platformsh-templates/drupal8-multisite/pull/6

Remove deprecated glue code.

---

.gitignore
README.md
project/rails.py
templates/rails/files/_boot.rb

I corrected the logic of the updater such as that it would stay on the same major version of rails.

Rails update

---

templates/rails/dont-ignore-database.yml
templates/rails/files/.platform.app.yaml
templates/rails/files/config/database.yml

cf: https://github.com/platformsh-templates/rails/pull/10

DB cleanup changes from Ori.

---

templates/typo3/.platform.template.yaml
templates/typo3/files/.platform.app.yaml
templates/typo3/files/README.md
templates/typo3/files/install-redis.sh

cf: https://github.com/platformsh-templates/typo3/pull/3

Use custom Redis extension for TYPO3, and bump to PHP 7.4.

---

templates/pimcore/.platform.template.yaml
templates/pimcore/files/.platform.app.yaml
templates/pimcore/files/README.md
templates/pimcore/files/install-redis.sh

cf: https://github.com/platformsh-templates/pimcore/pull/4

Update Pimcore template for custom compiled Redis extension.

---

templates/django3/files/myapp/settings.py

https://github.com/platformsh-templates/django3/pull/3

removes routes code

---

templates/django1/files/myapp/settings.py
templates/django2/files/myapp/settings.py

* https://github.com/platformsh-templates/django1/pull/5
* https://github.com/platformsh-templates/django2/pull/6

removes code from django1 and django2

---

templates/microprofile-tomee/files/pom.xml
templates/microprofile-tomee/files/src/main/resources/META-INF/beans.xml
templates/microprofile-tomee/files/src/test/resources/META-INF/beans.xml

Ref: https://github.com/platformsh-templates/microprofile-tomee/pull/5

updates apache tomee version

---

project/laravel.py

cf: https://github.com/platformsh-templates/laravel/pull/3

Use Laravel 7

---

templates/django1/files/Pipfile
templates/django1/files/Pipfile.lock
templates/django1/files/requirements.txt
templates/django2/files/Pipfile
templates/django2/files/Pipfile.lock

https://github.com/platformsh-templates/django1/pull/6 - django1 >= 1.11.28 
https://github.com/platformsh-templates/django2/pull/7 - django2 >= 2.2.10
Resolves https://github.com/platformsh/template-builder/pull/216
Resolves https://github.com/platformsh/template-builder/pull/202

Bump django templates.

---

templates/beego/.platform.template.yaml
templates/beego/files/.platform.app.yaml
templates/beego/files/README.md
templates/beego/files/go.mod
templates/echo/.platform.template.yaml
templates/echo/files/.platform.app.yaml
templates/echo/files/README.md
templates/echo/files/go.mod
templates/gin/.platform.template.yaml
templates/gin/files/.platform.app.yaml
templates/gin/files/README.md
templates/gin/files/go.mod
templates/golang/.platform.template.yaml
templates/golang/files/.platform.app.yaml
templates/golang/files/README.md
templates/golang/files/go.mod
templates/hugo/.platform.template.yaml
templates/hugo/files/.platform.app.yaml
templates/hugo/files/README.md
templates/hugo/files/build.sh

DEVREL-618
https://github.com/platformsh-templates/beego/pull/3
https://github.com/platformsh-templates/echo/pull/4
https://github.com/platformsh-templates/golang/pull/3
https://github.com/platformsh-templates/hugo/pull/3

Bump go templates to 1.14.

---

templates/mattermost/.platform.template.yaml
templates/mattermost/files/README.md

Removes duplicate initialize key that confuses DoP button

Remove template-yaml duplicate

---

templates/microprofile-helidon/files/pom.xml

https://github.com/platformsh-templates/microprofile-helidon/pull/7

Updates helidon version to 1.4.4

---

templates/nextcloud/files/.platform.app.yaml
templates/nextcloud/files/README.md
templates/nextcloud/files/_config/config.php

Easy small cleanups.  More to come.
https://github.com/platformsh-templates/nextcloud/pull/3

Nextcloud updates

---

templates/microprofile-kumuluzee/files/.platform.app.yaml
templates/microprofile-kumuluzee/files/.platform/routes.yaml
templates/microprofile-kumuluzee/files/pom.xml
templates/microprofile-kumuluzee/files/src/main/java/sh/platform/template/HelloWorldResource.java

https://github.com/platformsh-templates/microprofile-kumuluzee/pull/6

upgrades kumuluzee

---

templates/jenkins/files/.platform.app.yaml
templates/micronaut/files/.platform.app.yaml
templates/microprofile-helidon/files/.platform.app.yaml
templates/microprofile-kumuluzee/files/.platform.app.yaml
templates/microprofile-openliberty/files/.platform.app.yaml
templates/microprofile-payara/files/.platform.app.yaml
templates/microprofile-thorntail/files/.platform.app.yaml
templates/spring-boot-gradle-mysql/files/.platform.app.yaml
templates/spring-boot-maven-mysql/files/.platform.app.yaml
templates/spring-kotlin/files/.platform.app.yaml
templates/spring-mvc-maven-mongodb/files/.platform.app.yaml

Templates
* https://github.com/platformsh-templates/microprofile-thorntail/pull/7
* https://github.com/platformsh-templates/microprofile-payara/pull/9
* https://github.com/platformsh-templates/microprofile-openliberty/pull/7
* https://github.com/platformsh-templates/microprofile-helidon/pull/8
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/7
* https://github.com/platformsh-templates/spring-kotlin/pull/8
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/8
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/9
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/8
* https://github.com/platformsh-templates/micronaut/pull/6
* https://github.com/platformsh-templates/jenkins/pull/3

updates the java command

---

templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml

Updates the Spring version to 2.2.6
- https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/7
- https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/7
- https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/7
- https://github.com/platformsh-templates/spring-kotlin/pull/7

updates spring to version 2.2.6

---

templates/quarkus/files/README.md

https://github.com/platformsh-templates/quarkus/pull/2

creates button at quarkus

---

templates/quarkus/files/.platform.app.yaml

Ref: https://github.com/platformsh-templates/quarkus/pull/3

Removes mounts app folder

---

templates/gatsby-strapi/files/strapi/.platform.app.yaml
templates/strapi/files/backend/.platform.app.yaml

https://github.com/platformsh-templates/strapi/pull/3
https://github.com/platformsh-templates/gatsby-strapi/pull/3

Add .tmp mount, which now is required for strapi.

---

templates/django2/files/Pipfile
templates/django2/files/Pipfile.lock

cf https://github.com/platformsh-templates/django2/pull/9

Django security updates

---

project/wordpress.py

https://github.com/platformsh-templates/wordpress/pull/8

Change mv to cp for local case.

---

templates/quarkus/.platform.template.yaml
templates/quarkus/files/README.md
templates/quarkus/files/pom.xml

https://github.com/platformsh-templates/quarkus/pull/4

Update quarkus application

---

templates/microprofile-thorntail/files/pom.xml

https://github.com/platformsh-templates/microprofile-thorntail/pull/8

Updates thorntail to version 2.7.0

---

project/typo3.py
templates/typo3/files/README.md
templates/typo3/files/public/typo3conf/PlatformshConfiguration.php

cf:
https://github.com/platformsh/platformsh-docs/pull/1457
https://github.com/platformsh-templates/typo3/pull/7

Pre-load deadlock prevention tools for TYPO3

---

templates/gatsby-strapi/files/README.md
templates/gatsby-wordpress/files/README.md
templates/strapi/files/README.md

Descriptions for:
- strapi
- gatsby-strapi
- gatsby-wordpress

Gatsby and headless descriptions.

---

templates/drupal9/files/web/sites/default/settings.platformsh.php

cf: https://github.com/platformsh-templates/drupal9/pull/4

De-8-ify Drupal 9 override variables.

---

templates/microprofile-tomee/files/.platform.app.yaml
templates/microprofile-tomee/files/pom.xml

https://github.com/platformsh-templates/microprofile-tomee/pull/8

Update TomEE version

---

templates/drupal8-multisite/files/web/sites/settings.platformsh.php
templates/drupal8-opigno/files/web/sites/default/settings.platformsh.php
templates/drupal8/files/web/sites/default/settings.platformsh.php
templates/drupal9/files/web/sites/default/settings.platformsh.php

cf: 
https://github.com/platformsh-templates/drupal9/pull/5
https://github.com/platformsh-templates/drupal8/pull/22
https://github.com/platformsh-templates/drupal8-multisite/pull/11

Make Drupal settings files more fault-tolerant

---

templates/micronaut/files/.platform.app.yaml
templates/micronaut/files/pom.xml
templates/microprofile-helidon/files/.platform.app.yaml
templates/microprofile-helidon/files/pom.xml
templates/microprofile-helidon/files/src/main/java/sh/platform/template/GreetApplication.java

- https://github.com/platformsh-templates/micronaut/pull/9
- https://github.com/platformsh-templates/microprofile-helidon/pull/10

Update micronaut and helidon

---

templates/nextcloud/files/.platform.app.yaml
templates/nextcloud/files/download-nextcloud.sh

cf: https://github.com/platformsh-templates/nextcloud/pull/8

Upgrade to Nextcloud 19.

---

project/drupal.py

cf: https://github.com/platformsh-templates/drupal8-govcms8/pull/3

Fix GovCMS now that the upstream is more stable.

---

templates/laravel/.platform.template.yaml
templates/laravel/files/.platform.app.yaml
templates/laravel/files/README.md

cf: https://github.com/platformsh-templates/laravel/pull/10

Add Laravel mount mapping.

---

templates/spring-boot-gradle-mysql/files/.platform.app.yaml
templates/spring-boot-maven-mysql/files/.platform.app.yaml
templates/spring-kotlin/files/.platform.app.yaml
templates/spring-mvc-maven-mongodb/files/.platform.app.yaml

- https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/15
- https://github.com/platformsh-templates/spring-kotlin/pull/11
- https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/11
- https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/11

Update Spring templates to use Java 11

---

templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml

* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/16
* https://github.com/platformsh-templates/spring-kotlin/pull/12
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/12
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/12

Update spring version to 2.3.1

---

templates/microprofile-helidon/files/.platform.app.yaml
templates/microprofile-helidon/files/pom.xml
templates/microprofile-kumuluzee/files/.platform.app.yaml
templates/microprofile-kumuluzee/files/pom.xml
templates/microprofile-openliberty/files/.platform.app.yaml
templates/microprofile-openliberty/files/pom.xml
templates/microprofile-payara/files/.platform.app.yaml
templates/microprofile-payara/files/pom.xml
templates/microprofile-thorntail/files/.platform.app.yaml
templates/microprofile-thorntail/files/pom.xml
templates/microprofile-wildfly/files/pom.xml

* https://github.com/platformsh-templates/microprofile-wildfly/pull/4
* https://github.com/platformsh-templates/microprofile-payara/pull/12
* https://github.com/platformsh-templates/microprofile-thorntail/pull/10
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/10
* https://github.com/platformsh-templates/microprofile-helidon/pull/11
* https://github.com/platformsh-templates/microprofile-openliberty/pull/11

Update microprofiles implementations to use Java 11

---

templates/jenkins/files/.platform.app.yaml
templates/jetty/files/.platform.app.yaml
templates/jetty/files/pom.xml
templates/micronaut/files/.platform.app.yaml
templates/micronaut/files/pom.xml
templates/tomcat/files/.platform.app.yaml
templates/tomcat/files/pom.xml

* https://github.com/platformsh-templates/jenkins/pull/5
* https://github.com/platformsh-templates/jetty/pull/7
* https://github.com/platformsh-templates/micronaut/pull/10
* https://github.com/platformsh-templates/tomcat/pull/3

Update java 11

---

templates/jenkins/.platform.template.yaml
templates/jenkins/files/README.md
templates/jetty/.platform.template.yaml
templates/jetty/files/README.md
templates/micronaut/.platform.template.yaml
templates/micronaut/files/README.md
templates/microprofile-helidon/.platform.template.yaml
templates/microprofile-helidon/files/README.md
templates/microprofile-kumuluzee/.platform.template.yaml
templates/microprofile-kumuluzee/files/README.md
templates/microprofile-openliberty/.platform.template.yaml
templates/microprofile-openliberty/files/README.md
templates/microprofile-payara/.platform.template.yaml
templates/microprofile-payara/files/README.md
templates/microprofile-thorntail/.platform.template.yaml
templates/microprofile-thorntail/files/README.md
templates/microprofile-tomee/.platform.template.yaml
templates/microprofile-tomee/files/README.md
templates/spring-boot-gradle-mysql/.platform.template.yaml
templates/spring-boot-gradle-mysql/files/README.md
templates/spring-boot-maven-mysql/.platform.template.yaml
templates/spring-boot-maven-mysql/files/README.md
templates/spring-kotlin/.platform.template.yaml
templates/spring-kotlin/files/README.md
templates/spring-mvc-maven-mongodb/.platform.template.yaml
templates/spring-mvc-maven-mongodb/files/README.md
templates/tomcat/.platform.template.yaml
templates/tomcat/files/README.md
templates/xwiki/.platform.template.yaml
templates/xwiki/files/README.md

* https://github.com/platformsh-templates/jenkins/pull/6
* https://github.com/platformsh-templates/jetty/pull/8
* https://github.com/platformsh-templates/micronaut/pull/11
* https://github.com/platformsh-templates/microprofile-payara/pull/13
* https://github.com/platformsh-templates/microprofile-thorntail/pull/11
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/11
* https://github.com/platformsh-templates/microprofile-openliberty/pull/12
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/17
* https://github.com/platformsh-templates/spring-kotlin/pull/13
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/13
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/13
* …

Update java 11 documentation

---

project/drupal.py
templates/drupal8-govcms8/.platform.template.yaml
templates/drupal8-govcms8/files/.platform.app.yaml
templates/drupal8-govcms8/files/.platform/services.yaml
templates/drupal8-govcms8/files/README.md

cf: https://github.com/platformsh-templates/drupal8-govcms8/pull/7

GovCMS corrections

---

templates/wordpress/files/README.md

https://github.com/platformsh-templates/wordpress/pull/15

Adds community links.

---

templates/drupal8-govcms8/files/.platform.app.yaml

cf: https://github.com/platformsh-templates/drupal8-govcms8/pull/11

Don't run the Drupal deploy commands on first deploy

---

project/laravel.py

cf https://github.com/platformsh-templates/laravel/pull/15

Bump Laravel major version.

---

templates/quarkus/files/pom.xml

https://github.com/platformsh-templates/quarkus/pull/7

Updates quarkus version to 1.7.3

---

templates/micronaut/files/pom.xml
templates/microprofile-helidon/files/pom.xml
templates/microprofile-openliberty/files/pom.xml

* https://github.com/platformsh-templates/micronaut/pull/13
* https://github.com/platformsh-templates/microprofile-helidon/pull/14
* https://github.com/platformsh-templates/microprofile-openliberty/pull/14

Update Java templates

---

templates/typo3/files/.platform.app.yaml
templates/typo3/files/.platform/routes.yaml
templates/typo3/files/.platform/services.yaml
templates/typo3/files/config/sites/main/config.yaml
templates/typo3/files/public/typo3conf/PlatformshConfiguration.php

https://github.com/platformsh-templates/typo3/pull/12

Improve TYPO3 comments for guide.

---

dodo.py
project/nextjs.py
templates/nextjs/files/.platform.app.yaml

https://github.com/platformsh-templates/nextjs/pull/3

Update start command to use npx next.

---

project/wordpress.py

https://github.com/platformsh-templates/wordpress/pull/17

Adds wppackagist repo.

---

templates/drupal8-govcms8/files/docroot/sites/default/settings.platformsh.php
templates/drupal8-multisite/files/web/sites/settings.platformsh.php
templates/drupal8-opigno/.platform.template.yaml
templates/drupal8-opigno/files/.platform.app.yaml
templates/drupal8-opigno/files/web/sites/default/settings.platformsh.php
templates/drupal8/files/web/sites/default/settings.platformsh.php
templates/drupal9/files/web/sites/default/settings.platformsh.php

cf:
https://github.com/platformsh-templates/drupal8/pull/30
https://github.com/platformsh-templates/drupal8-opigno/pull/16
https://github.com/platformsh-templates/drupal8-govcms8/pull/13
https://github.com/platformsh-templates/drupal8-multisite/pull/17
https://github.com/platformsh-templates/drupal9/pull/13

Enable verbose logging on non-production environments.

---

templates/drupal8-govcms8/files/docroot/sites/default/settings.platformsh.php

Remove debug line.

---

templates/strapi/files/backend/.platform.app.yaml

https://github.com/platformsh-templates/strapi/pull/8

Downgrade NodeJS version in Strapi project

---

templates/micronaut/files/pom.xml
templates/quarkus/files/pom.xml

* https://github.com/platformsh-templates/quarkus/pull/8
* https://github.com/platformsh-templates/micronaut/pull/14

Update Quarkus and Micronaut

---

templates/microprofile-kumuluzee/files/pom.xml
templates/microprofile-wildfly/files/pom.xml

* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/13
* https://github.com/platformsh-templates/microprofile-wildfly/pull/5

Updates Widfly and kumuluzee version

---

project/wordpress.py
templates/wordpress/files/.platform.app.yaml

https://github.com/platformsh-templates/wordpress/pull/20

Fix in container wp-cli.

---

templates/micronaut/files/pom.xml
templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml
templates/tomcat/files/pom.xml

* https://github.com/platformsh-templates/micronaut/pull/15
* https://github.com/platformsh-templates/tomcat/pull/6
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/19
* https://github.com/platformsh-templates/spring-kotlin/pull/15
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/15
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/15

Update java library

---

templates/golang/.platform.template.yaml
templates/golang/files/.platform.app.yaml
templates/golang/files/go.mod

cf: https://github.com/platformsh-templates/golang/pull/5

Update to Go 1.15.

---

templates/laravel/files/.lando.upstream.yml
templates/laravel/files/install-redis.sh
templates/symfony5/files/.lando.upstream.yml

@Crell and @pirog to review this

Add default lando config for some symfony based templates

---

templates/nodejs/files/index.js

The idea was to bring some consistency across the code example.
- No `let` if we don't re-assign variables
- No need for a function to be `async` when it returns a Promise. We can `await` for this promise where the function is called.
- Some parts were abstracted in functions and others weren't. All database operations are now in their own functions.
- Naming convention (everything was camelCase except for `dropped_result`.)
- Reorganise `require`s to have the native packages first and then external dependencies.

clean nodejs template code

---

templates/express/files/index.js

Same changes as the node template.

clean express template code

---

templates/drupal8-govcms8/files/.lando.upstream.yml
templates/drupal8-multisite/files/.lando.upstream.yml
templates/drupal8-opigno/files/.lando.upstream.yml

cf:
https://github.com/platformsh-templates/drupal8-multisite/pull/18
https://github.com/platformsh-templates/drupal8-opigno/pull/17
https://github.com/platformsh-templates/drupal8-opigno/pull/17
https://github.com/platformsh-templates/drupal8-govcms8/pull/15
https://github.com/platformsh-templates/drupal9/pull/15

Add Lando files to all the Drupals.

---

templates/microprofile-helidon/files/pom.xml

https://github.com/platformsh-templates/microprofile-helidon/pull/15

Updates Helidon version to 2.1.0

---

templates/strapi/files/.platform.app.yaml

https://github.com/platformsh-templates/strapi/pull/19
- You can locally develop your API, which will then be written to these subdirectories.
- If you then push to P.sh, they become mounts and are overwritten. 
- This allows local changes to be pushed to environments for the api.

Strapi mount dance for api and exports.

---

templates/hugo/.platform.template.yaml
templates/hugo/files/.platform.app.yaml
templates/hugo/files/README.md

https://github.com/platformsh-templates/hugo/pull/9

Update Hugo and Go versions.

---

templates/magento2ce/files/README.md
templates/wordpress/files/.platform.app.yaml
templates/wordpress/files/README.md
templates/wordpress/files/plugins/README.txt

https://github.com/platformsh-templates/wordpress/pull/21

Wordpress Lando and improved plugin support

---

templates/laravel/files/.lando.upstream.yml

cf: https://github.com/platformsh-templates/laravel/pull/23

Set log level to debug in local laravel lando development.

---

templates/typo3/files/.platform.app.yaml

https://github.com/platformsh-templates/typo3/pull/14

Support lando rebuild. Don't run install:setup after first deploy.

---

templates/quarkus/files/pom.xml

https://github.com/platformsh-templates/quarkus/pull/10

Updates quarkus version to 1.9.1

---

templates/laravel/files/.platform.app.yaml

cf https://github.com/platformsh-templates/laravel/pull/24

Add cron and worker config to Laravel.

---

templates/strapi/files/.platform.app.yaml

https://github.com/platformsh-templates/strapi/pull/21

Add components mount to strapi.

---

templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml

* https://github.com/platformsh-templates/spring-kotlin/pull/16
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/20
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/18
* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/16

Updates Spring templates libraries

---

project/backdrop.py

Fixes https://github.com/platformsh/template-builder/issues/376

Update Backdrop version to 1.17.3

---

templates/php/files/.lando.upstream.yml
templates/sculpin/files/.lando.upstream.yml

cf
https://github.com/platformsh-templates/php/pull/5
https://github.com/platformsh-templates/sculpin/pull/17

Add more Lando config files.

---

templates/micronaut/files/pom.xml

https://github.com/platformsh-templates/micronaut/pull/17

updates micronaut version to 2.2

---

templates/quarkus/files/pom.xml

https://github.com/platformsh-templates/quarkus/pull/11

updates quarkus to version 1.9.2

---

project/symfony.py

Related Symfony updates:
https://github.com/platformsh-templates/symfony5/pull/17
https://github.com/platformsh-templates/symfony4/pull/20
https://github.com/platformsh-templates/symfony3/pull/13

Fix platform flag on Symfony.

---

templates/wordpress-composer/files/wp-config.php

https://github.com/platformsh-templates/wordpress-composer/pull/2

Remove auto-updates from wp-composer.

---

dodo.py
project/wordpress.py
templates/wordpress-bedrock/.platform.template.yaml
templates/wordpress-bedrock/files/.environment
templates/wordpress-bedrock/files/.lando.upstream.yaml
templates/wordpress-bedrock/files/.platform.app.yaml
templates/wordpress-bedrock/files/.platform/routes.yaml
templates/wordpress-bedrock/files/.platform/services.yaml
templates/wordpress-bedrock/files/README.md

https://github.com/platformsh-templates/wordpress-bedrock/pull/1

WordPress Bedrock

---

templates/spring-boot-gradle-mysql/files/.platform.app.yaml
templates/spring-boot-gradle-mysql/files/build.gradle
templates/spring-boot-gradle-mysql/files/settings.gradle
templates/spring-boot-maven-mysql/files/pom.xml
templates/spring-kotlin/files/pom.xml
templates/spring-mvc-maven-mongodb/files/pom.xml

* https://github.com/platformsh-templates/spring-boot-maven-mysql/pull/17
* https://github.com/platformsh-templates/spring-boot-gradle-mysql/pull/19
* https://github.com/platformsh-templates/spring-kotlin/pull/17
* https://github.com/platformsh-templates/spring-mvc-maven-mongodb/pull/21

Update Spring templates

---

templates/micronaut/files/pom.xml
templates/microprofile-kumuluzee/files/pom.xml
templates/microprofile-payara/files/pom.xml
templates/microprofile-thorntail/files/pom.xml
templates/microprofile-tomee/files/pom.xml
templates/microprofile-wildfly/files/pom.xml

* https://github.com/platformsh-templates/micronaut/pull/19
* https://github.com/platformsh-templates/microprofile-payara/pull/16
* https://github.com/platformsh-templates/microprofile-wildfly/pull/7
* https://github.com/platformsh-templates/microprofile-thorntail/pull/12
* https://github.com/platformsh-templates/microprofile-tomee/pull/13
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/14

Optimize microprofile

---

templates/wordpress-composer/.platform.template.yaml
templates/wordpress-composer/files/README.md

cf https://github.com/platformsh-templates/wordpress-composer/pull/5
Resolves https://github.com/platformsh/template-builder/pull/397

Correct typo in README.

---

templates/micronaut/files/pom.xml
templates/microprofile-kumuluzee/files/pom.xml
templates/quarkus/files/pom.xml
templates/quarkus/files/src/main/resources/META-INF/resources/index.html

* https://github.com/platformsh-templates/micronaut/pull/20
* https://github.com/platformsh-templates/quarkus/pull/13
* https://github.com/platformsh-templates/microprofile-kumuluzee/pull/15

Update Micronaut, Quarkus and Kumuluzee template

---

templates/directus/.platform.template.yaml
templates/directus/files/.environment
templates/directus/files/.platform.app.yaml
templates/directus/files/.platform/services.yaml
templates/directus/files/README.md

https://github.com/platformsh-templates/directus/pull/4

Directus: redis for cache and rate-limit.

---

templates/directus/files/.environment

Final follow up to https://github.com/platformsh/template-builder/pull/400, only because I hadn't pushed during the rounds of review. 
Already merged into template (https://github.com/platformsh-templates/directus/pull/4) here: https://github.com/platformsh-templates/directus/blob/7ed9658724aedc3b830c9635c9970b8e71b0d189/.environment#L34

Match Rate limiter env var definition.

---

templates/microprofile-payara/files/pom.xml
templates/quarkus/files/pom.xml
templates/quarkus/files/src/main/resources/META-INF/resources/index.html

- https://github.com/platformsh-templates/microprofile-payara/pull/17
- https://github.com/platformsh-templates/quarkus/pull/14

Updates Payara and Quarkus version

---

templates/strapi/files/.platform.app.yaml

https://github.com/platformsh-templates/strapi/pull/28

fix typo in strapi app yaml

---

templates/drupal8-govcms8/platformsh.wizard.yaml
templates/drupal8-multisite/platformsh.wizard.yaml
templates/drupal8-opigno/platformsh.wizard.yaml
templates/drupal9/platformsh.wizard.yaml
templates/wordpress-bedrock/platformsh.wizard.yaml
templates/wordpress-composer/platformsh.wizard.yaml
templates/wordpress-woocommerce/platformsh.wizard.yaml

Extends https://github.com/platformsh/template-builder/pull/422

Add wizard files for additional Drupal/WP templates.

---

templates/strapi/files/.platform.app.yaml
templates/strapi/files/.platform/services.yaml
templates/strapi/files/README.md

Strapi template update PR: https://github.com/platformsh-templates/strapi/pull/46

add update files to strapi template

---

templates/strapi/files/README.md

Strapi template PR: https://github.com/platformsh-templates/strapi/pull/47/

update readme in strapi docs

---

templates/drupal8-govcms8/.platform.template.yaml
templates/drupal8-multisite/.platform.template.yaml
templates/drupal8-opigno/.platform.template.yaml

- opigno
- govcms8
- multisite

update ID and Repository initialize field for drupal8 templates

---

templates/drupal8-govcms8/platformsh.wizard.yaml
templates/drupal8-multisite/platformsh.wizard.yaml
templates/drupal8-opigno/platformsh.wizard.yaml
templates/drupal8/platformsh.wizard.yaml
templates/drupal9/platformsh.wizard.yaml
templates/strapi/platformsh.wizard.yaml
templates/strapi4/platformsh.wizard.yaml
templates/wordpress-bedrock/platformsh.wizard.yaml
templates/wordpress-composer/platformsh.wizard.yaml
templates/wordpress-vanilla/platformsh.wizard.yaml
templates/wordpress-woocommerce/platformsh.wizard.yaml

Updates references from "master" branch to "main" in templates' platformsh.wizard.yaml file

Updates references from "master" branch to "main" 

---

templates/strapi/files/README.md

Accompanying PR: https://github.com/platformsh-templates/strapi/pull/67

update strapi3 readme

---

.github/workflows/updates.yaml

Places template updates on a schedule. 
Two issues will still need to be addressed after this.
- https://github.com/platformsh/template-builder/issues/504
- https://github.com/platformsh/template-builder/issues/501

Place updates on a schedule.

---

project/backdrop.py

Fixes https://github.com/platformsh/template-builder/issues/506

Update backdrop.py to Backdrop 1.21.1

---

.github/workflows/updates.yaml

Bulk of step 4 was moved into a reusable github action. updates the workflow to use this action.

Alters Step 4 to use the platformsh/prep-for-autopr@main github action

---

templates/django2/files/README.md

Update Python2 version in Django 2 template

---

templates/laravel/files/.blackfire.yaml
templates/laravel/files/.platform.app.yaml

Laravel template PR: https://github.com/platformsh-templates/laravel/pull/36

Add .blackfire.yaml file to the Laravel template

---

templates/drupal9/files/.platform.app.yaml
templates/drupal9/files/platformsh_deploy_drush.sh

Pairs with https://github.com/platformsh-templates/drupal9/pull/119 so nothing gets overwritten on auto-updates

Drupal9 drush improvements.

---

project/mattermost.py

Adds ?per_page=100 to the github api call so we can retrieve enough results in order to find the v6 tags
Closes #652

Adds ?per_page=100 to the github api call 

---

dodo.py
templates/drupal9/files/.platform.app.yaml
templates/drupal9/files/README.md

Fixes https://github.com/platformsh/template-builder/issues/692
Provides an update to Drupal 9 for https://github.com/platformsh/template-builder/issues/693, which will need to be applied to all templates that have crons defined. 
There's also a stray link output into the Drupal 9 README file that's removed.

Cron fix, single template pass.

---

templates/backdrop/.platform.template.yaml
templates/backdrop/files/.platform.app.yaml
templates/gatsby-wordpress/.platform.template.yaml
templates/gatsby-wordpress/files/wordpress/.platform.app.yaml
templates/wordpress-composer/.platform.template.yaml
templates/wordpress-composer/files/.platform.app.yaml

Updates 
* wordpress-composer
* gatsby-composer
* backdrop
templates to PHP 8.1. Partial fix for #703

Updates some templates to php 8.1

---

common/sourceop-auto-update/.github/workflows/sourceops.yaml

Corrects the URL to the sourceop setup file. Closes #715

Corrects the URL to the sourceop setup file.

---

project/backdrop.py
templates/backdrop/files/.platform.app.yaml
templates/backdrop/files/README.md

Here is the latest release of Backdrop:
https://github.com/backdrop/backdrop/releases/latest
This resolves issue #720

Updating Backdrop to latest release 1.23.1

---

templates/nextjs/files/.platform.app.yaml
templates/nextjs/files/handle_mounts.sh
templates/nextjs/files/next.config.js
templates/nextjs/files/package-lock.json
templates/nextjs/files/yarn.lock

This PR updates the NextJS template to prevent it from ending up with orphan” processes.

update nextjs files

---

common/sourceop-auto-update/.github/workflows/sourceops.yaml

changes environmental variable name for platform project id from PLATFORMSH_PROJECT to PLATFORM_PROJECT
Closes #763

Update environmental variable name

---

.github/workflows/updates.yaml

updates set-output command to new format

---

archived/contentacms/platformsh.wizard.yaml
templates/drupal10/platformsh.wizard.yaml
templates/drupal8-govcms8/platformsh.wizard.yaml
templates/drupal8-multisite/platformsh.wizard.yaml
templates/drupal8-opigno/platformsh.wizard.yaml
templates/drupal8/platformsh.wizard.yaml
templates/drupal9-govcms9/platformsh.wizard.yaml
templates/drupal9-multisite/platformsh.wizard.yaml
templates/drupal9/platformsh.wizard.yaml
templates/strapi/platformsh.wizard.yaml
templates/strapi4/platformsh.wizard.yaml
templates/wordpress-bedrock/platformsh.wizard.yaml
templates/wordpress-composer/platformsh.wizard.yaml
templates/wordpress-vanilla/platformsh.wizard.yaml
templates/wordpress-woocommerce/platformsh.wizard.yaml

Updates link for the platform.sh cli source code in the wizard files. Closes #801

Updates link to platform.sh cli code

---

.github/workflows/updates.yaml
templates/nuxtjs/.platform.template.yaml

To be merged alongside https://github.com/platformsh-templates/nuxtjs/pull/72
- skips workflow until synced.
- Updates template.yaml for catalog

Skip nuxtjs updates until synced.
