symfony3/files/.platform.app.yaml, symfony3/files/app/config/parameters_platformsh.php, symfony3/parameters.patch
* Fix bug in the patch file.
* Switch to PHP 7.2.
* Resync with the -example repo.
This is now ready to be made the canonical Symfony 3 starter kit.
=> Symfony 3 update

symfony4/files/.platform.app.yaml
=> Use PHP 7.2 for Symfony 4.

laravel/files/README.md
1) Pointing out the phpredis patch that we made
2) Also making it more clear that redis is being used by default as Laravel's cache and session driver (vanilla Laravel uses a different default for these).
=> Laravel - updating readme to include changes we made

dodo.py, drupal7/files/project.make
Easier maintenance this way.
This also includes version upgrades for WordPress, Symfony4, and Drupal 7.
=> Move version numbers to a central lookup list

project/__init__.py, project/remote.py
Old code: Auto-update composer on all remote projects, even if they weren't PHP.
New code: Auto-update each language's package manager if the file is there, for all projects.
=> Language updates

project/laravel.py, project/magento.py, project/remote.py, project/symfony.py, project/wordpress.py, templates/magento2ce/platformsh.patch
I've tested this against Laravel, but not the other projects yet.  But it does remove an annoying bit of hard coding in a nice way.
Also, we have to keep upstream_branch as the Drupal Composer upstream project... has no tags.  It's just an 8.x branch that wraps whatever the latest tagged version of Drupal is.  So... *sigh*
Drupal 7 is also an oddball since that needs updates to the makefile, not just to the definition class.  That hasn't been addressed yet here.
=> Automatically dereive the latest tag for a remote project to merge from

templates/drupal7/files/.platform.template.yaml, templates/drupal7/files/project.make
Drupal security updates: https://www.drupal.org/sa-core-2019-007
See also:
https://github.com/platformsh/template-drupal8/pull/43
https://github.com/platformsh/template-drupal7/pull/14
=> Update Drupal7 and Drupal8 templates for security update.

project/magento.py, templates/magento2ce/files/.platform.app.yaml
What's not shown here is that I had to do a manual update of Magento itself as it had Git file conflicts with... itself.  I don't fully understand why.  Also, Magento is huge.
The patch file has some line offsets but still applies.  I have not modified it but to avoid stray .orig files in the future we may want to reroll it at some point.
This also switches to PHP 7.2, which requires removing mcrpyt as that's been removed in 7.2.
This does build: https://github.com/platformsh/template-magento2ce/pull/8
However, to really make sure everything works I think we'll need to update the repo, then try to do a second update and make sure everything in this PR "takes" properly.  I'm not sure if a better way.
=> Switch to Magento 2.3

project/symfony.py
The latest update to Symfony adds a minimum-stability of "dev".  I don't know why.  But for some reason that is causing the default chosen version of symfonyflex-bridge to become 1.0@dev instead of the latest, which is 2.1.  I don't know why that happens, either.  But explicitly specifying a minimum version here works around that adequately so it works for now.
=> Make the minimum version of symfonyflex-bridge explicit

templates/django2/files/myapp/settings.py
Because the SECRET_KEY is being reset further down, I'm not sure if this is necessary.  The alternative would be to just change the comment to indicate that in prod a different value would be used, but the current status freaked out both Dan and myself as a security concern, even if it's not really one after all.  So we should do something. :smile:
=> Don't set a default secret key, even for local use.

templates/akeneo/.platform.template.yaml
The initialize.repository key in templates _only_ supports Git-protocol or HTTPS-protocol URIs, not SSH.
=> Fix Akeneo initialize.repository key

templates/drupal8/files/web/sites/default/settings.platformsh.php, templates/drupal8multi/files/web/sites/settings.platformsh.php, templates/opigno/files/web/sites/default/settings.platformsh.php
in case the Redis module itself is missing.
cf:
https://github.com/platformsh/template-drupal8/pull/51
https://github.com/platformsh/template-opigno/pull/3
https://github.com/platformsh/template-drupal8multi/pull/5
(govcms8 not included because it's settings.platformsh.php file is well behind anyway and it has other issues that need fixing first.)
=> Include a check in Drupal Redis integration

templates/drupal8/files/drush/platformsh_drush.inc, templates/drupal8multi/.platform.template.yaml, templates/drupal8multi/files/README.md, templates/drupal8multi/files/drush/platformsh_drush.inc, templates/drupal8multi/files/web/sites/settings.platformsh.php, templates/drupal8multi/files/web/sites/sites.php, templates/govcms8/files/drush/platformsh_drush.inc, templates/govcms8/files/web/sites/default/settings.platformsh.php, templates/opigno/files/drush/platformsh_drush.inc, templates/opigno/files/web/sites/default/settings.platformsh.php
* Update the Drush URL derivation.
* Remove all trusted-host logic as it's no longer needed.
* Use the new config reader functionality in the D8 multisite logic.
Related:
* https://github.com/platformsh/template-drupal8/pull/52
* https://github.com/platformsh/template-drupal8multi/pull/6
* https://github.com/platformsh/template-opigno/pull/4
* No GovCMS8 yet as that still needs work for other reasons
=> Clean up and expand config reader usage in Drupal

Pipfile, Pipfile.lock, project/remote.py
Now it excludes beta/alpha tags, and handles version segments greater than 9.
=> Fix multiple bugs in the latest-tag derivation logic. 

templates/mautic/ignore.patch
Why it is excluding its own translations directory, which it needs to run, I do not know.
https://github.com/platformsh-templates/mautic/pull/3
=> Don't exclude the translations directory.

project/backdrop.py, templates/backdrop/files/README.md
I'm not sure why this wasn't already there, but let's fix that.
Also, how did the command ever work with the rm command wrong?
cf: https://github.com/platformsh-templates/backdrop/pull/2
=> Add DoP button to Backdrop.

templates/wordpress/files/.platform/routes.yaml
Cookies beginning with `wp-postpass_(HASH)` are [used by Wordpress to provide one-off page passwords](https://wordpress.org/support/article/using-password-protection/
). 
From user feedback in [#platformsh Slack 2020-01-10](https://platformsh.slack.com/archives/C0JHEUHQD/p1578633384485700?thread_ts=1578631656.485400&cid=C0JHEUHQD) 
Currently this cookie is stripped by the cache layer, and not making it back to the server, so this core wordpress functionality fails.
Maybe we should have it in our wordpress template.
The [nginx blog endorses that, with its example]( https://www.nginx.com/blog/9-tips-for-improving-wordpress-performance-with-nginx/) of how to tune caching for wordpress. Their example includes this cookie pattern as one not to cache.
Also recommended in [Wordpress docs for …
=> Add wp-postpass to cookie whitelist

templates/strapi/files/backend/build.sh, templates/strapi/files/backend/platformsh/index.html
Related to https://github.com/platformsh/template-builder/pull/179#issuecomment-575819764
Since [getPrimaryRoute](https://github.com/platformsh/config-reader-nodejs/pull/11/files) is not accessible during the build phase, I hardcoded the admin URL in the `index.html` file, which is replaced during the build phase.
=> Fix create first admin link

project/symfony.py, templates/symfony4/ignore-env.patch, templates/symfony5/ignore-env.patch
Otherwise Flex tries to pin to PHP 7.4 on my computer, and then won't run on 7.3.  Because that makes sense.
cf: 
https://github.com/platformsh-templates/symfony4/pull/7
https://github.com/platformsh-templates/symfony5/pull/4
=> Pin Flex-based projects to a specific PHP target version.

templates/micronaut/files/.platform.app.yaml, templates/micronaut/files/pom.xml, templates/micronaut/files/src/main/java/sh/platform/template/Application.java, templates/micronaut/files/src/test/java/sh/platform/template/AppTest.java, templates/micronaut/files/src/test/resources/META-INF/beans.xml, templates/microprofile-helidon/files/.platform.app.yaml, templates/microprofile-helidon/files/pom.xml, templates/microprofile-kumuluzee/files/.platform.app.yaml, templates/microprofile-kumuluzee/files/pom.xml, templates/microprofile-kumuluzee/files/src/test/java/sh/platform/template/AppTest.java, templates/microprofile-kumuluzee/files/src/test/resources/META-INF/beans.xml, templates/microprofile-openliberty/files/pom.xml, templates/microprofile-openliberty/files/src/test/java/sh/platform/template/AppTest.java, templates/microprofile-openliberty/files/src/test/resources/META-INF/beans.xml, templates/microprofile-payara/files/.platform.app.yaml, templates/microprofile-thorntail/files/.platform.app.yaml, templates/microprofile-thorntail/files/pom.xml, templates/microprofile-thorntail/files/src/test/java/sh/platform/template/AppTest.java, templates/microprofile-thorntail/files/src/test/resources/META-INF/beans.xml, templates/microprofile-tomee/files/.platform.app.yaml, templates/microprofile-tomee/files/pom.xml, templates/microprofile-tomee/files/src/test/java/sh/platform/template/AppTest.java, templates/microprofile-tomee/files/src/test/resources/META-INF/beans.xml
This PR has the goal of updating the Eclipse MicroProfile version into the MicroProfile implementations. Therefore, it will remove deprecated annotations and create a test context and update the JUnit to JUnit Jupiter 5.6.0.
* [Updates the test unit framework to Junit Jupiter 5.6.0](https://junit.org/junit5/docs/snapshot/release-notes/#release-notes-5.6.0)
* Updates Eclipse MicroProfile Libraries
* Removes deprecated annotations in Micronauts
* Creates test scope to all Eclipse Microprofile templates
- https://github.com/platformsh-templates/microprofile-payara/pull/6
- https://github.com/platformsh-templates/microprofile-tomee/pull/3
- https://github.com/platformsh-templates/microprofile-kumuluzee/pull/4
- https://github.com/platformsh-templates/microprofile-helidon/pull/5
- …
=> Update Eclipse MicroProfile versions and create test scope.

project/remote.py, templates/magento2ce/files/.platform.app.yaml
Includes suggested fixes for outstanding issues, but those seem to not resolve those issues.  Still, we can iterate from here, and this includes a bug fix for the wipe-before-merge routine.
=> Magento 2.3.4 upgrade

project/symfony.py, templates/symfony3/files/.platform.app.yaml
One of its dependencies just made that its minimum version to be a putz.
=> Bump Symfony 3 to use PHP 7.4

templates/elastic-apm/files/kibana/.platform.app.yaml
A couple of small errors in the template. It should be : 
```                                export ES_USER=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".elasticsearch[0].username")
export ES_PASS=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq -r ".elasticsearch[0].password")
``` 
You wrote `user` rather than `username` and no `-r` for password. Also had some extra spaces around the variables..) Also ES_USER and ES_PASS are not magical they don't get passed. Simpler to pass the thing anyway as parameters at the `start` command directly.
=> Correct username and password.

templates/gatsby-wordpress/files/gatsby/gatsby-config.js
Backend was not actually being pulled from previous configuration, but wasn't failing either because it was previously setup using the route rather than the relationship. 
This fixes that first install experience to do it the right way.
https://github.com/platformsh-templates/gatsby-wordpress/pull/2
=> Fixes baseURL and protocol.

templates/drupal8-multisite/files/README.md
Using a Drush command on a specific sub-site may not be intuitive for users new to Drupal multi-sites setup although this multi-site template makes it quite easy, providing the right spell is casted
=> Adding instructions in readme.md to use Drush commands in multi-site setup

templates/drupal8-opigno/files/.platform.app.yaml, templates/drupal8-opigno/files/README.md
Unclear why, but it's still not working in Opigno even if it works for vanilla Drupal.
cf: https://github.com/platformsh-templates/drupal8-opigno/pull/6
=> Disable Redis in the installer.

templates/strapi/files/backend/build.sh, templates/strapi/files/backend/platformsh/index.html
We had a comment in #platformsh that the first `/admin` link button was directing to `localhost` again. This is the updated `index.html` file to fix that  from strapi, which we're already using in `gatsby-strapi`.
https://github.com/platformsh-templates/strapi/pull/2
=> Updates strapi admin link with new index.html patch file.

templates/microprofile-openliberty/files/.platform.app.yaml
https://github.com/platformsh-templates/microprofile-openliberty/pull/8
=> Adds an instruction to remove the open liberty workspace before start.

templates/drupal8-multisite/files/web/sites/settings.platformsh.php, templates/drupal8-opigno/files/web/sites/default/settings.platformsh.php, templates/drupal8/files/web/sites/default/settings.platformsh.php, templates/drupal9/files/web/sites/default/settings.platformsh.php
I must have missed this one when updating the others previously?  Or it changed later?  Not sure.
Resolves https://github.com/platformsh-templates/drupal8/pull/23
cf:
https://github.com/platformsh-templates/drupal8/pull/24
https://github.com/platformsh-templates/drupal8-multisite/pull/12
https://github.com/platformsh-templates/drupal8-opigno/pull/11
https://github.com/platformsh-templates/drupal9/pull/6
=> Update settings files for the temp path config having changed.

project/symfony.py, templates/symfony3/.platform.template.yaml, templates/symfony3/files/README.md
https://github.com/platformsh-templates/symfony3/pull/9
Adds  `composer update --no-plugins`, due to this message
```
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^2.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
```
It is the last command in `platformify`, which then returns
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Downgrading ocramius/package-versions (1.10.0 => 1.9.0): Loading from cache
```
Before this change, Symfony fails on Platform.sh:
```
Found 1 new commit
Building application 'app' (runtime type: php:7.4, tree: 8a2cd25) …
```
=> Symfony 3 not 4.

templates/directus/files/.environment
DEVREL-940
Parsing the default `STORAGE_LOCATIONS` results in an error on our side - so this fixes that in our `.environment` overrides. 
It also updates the public url settings for uploads, and adds some comments.
https://github.com/platformsh-templates/directus/pull/2
=> Fix uploads config for Directus

templates/akeneo/files/.platform.app.yaml, templates/akeneo/files/.platform/services.yaml
Current Akeneo template doesn't mount media files, so you can not view uploaded images. Additionally if you try to import something with Akeneo importers it will not work because your uploaded files are located in app, but importer daemon works in app-queue, I added another configuration to share job files between app & app-queue with network storage.
=> mount media files, sharing import files

templates/typo3/files/.lando.upstream.yml
@Crell and @pirog to review. Specifically need to discuss:
* Any TYPO3 envvars we need to set that are best for the localdevs?
* `lando rebuild` fails because the `build` hook tries to reinstall TYPO3 even though it's already installed? Should we make the install conditional?
This should be considered a draft for now.
=> Add good Lando defaults for the TYPO3 template

templates/directus/.platform.template.yaml, templates/directus/files/.environment, templates/directus/files/.platform.app.yaml, templates/directus/files/.platform/services.yaml, templates/directus/files/README.md, templates/directus/files/package-lock.json, templates/directus/files/package.json
https://github.com/platformsh-templates/directus/pull/3
Also removes the stray `https:` auth directory from template-builder, and adds Redis and memcached support to the template.
=> Add email support to Directus.

templates/akeneo/files/.platform.app.yaml, templates/drupal8-multisite/files/.platform.app.yaml, templates/drupal8-opigno/files/.platform.app.yaml, templates/drupal8/files/.platform.app.yaml, templates/drupal9/files/.platform.app.yaml, templates/gatsby-drupal/files/drupal/.platform.app.yaml, templates/gatsby-wordpress/files/wordpress/.platform.app.yaml, templates/laravel/files/.platform.app.yaml, templates/sculpin/files/.platform.app.yaml, templates/symfony4/files/.platform.app.yaml, templates/symfony5/files/.platform.app.yaml, templates/typo3/files/.platform.app.yaml, templates/wordpress-bedrock/files/.platform.app.yaml, templates/wordpress-composer/files/.platform.app.yaml, templates/wordpress-woocommerce/files/.platform.app.yaml
The ones not listed here broke in local build, likely due to API compatibility issues in Composer plugins.
Merged:
~https://github.com/platformsh-templates/drupal8/pull/41~
~https://github.com/platformsh-templates/laravel/pull/27~
~https://github.com/platformsh-templates/symfony4/pull/22~
~https://github.com/platformsh-templates/symfony5/pull/21~
~https://github.com/platformsh-templates/wordpress-bedrock/pull/3~
~https://github.com/platformsh-templates/wordpress-composer/pull/6~
~https://github.com/platformsh-templates/wordpress-woocommerce/pull/2~
~https://github.com/platformsh-templates/sculpin/pull/19~
~https://github.com/platformsh-templates/drupal8-multisite/pull/22~
~https://github.com/platformsh-templates/drupal9/pull/22~
App isn't ready yet: …
=> Switch to Composer 2 for most PHP projects.

templates/gatsby-wordpress/.platform.template.yaml, templates/wordpress-bedrock/.platform.template.yaml, templates/wordpress-composer/.platform.template.yaml
Capitalizing the "P" in WordPress on templates that had it written as Wordpress. (Change made at request of content team, primarily out of concern for it being correct when template info is pulled into https://platform.sh/)
=> Wordpress capitalization

templates/wordpress-bedrock/files/.platform.app.yaml
From [wordpress-bedrock](https://github.com/platformsh-templates/wordpress-bedrock), fixes issues [#11](https://github.com/platformsh-templates/wordpress-bedrock/issues/11), [#12](https://github.com/platformsh-templates/wordpress-bedrock/issues/12), and [#13](https://github.com/platformsh-templates/wordpress-bedrock/issues/13).  
all updates in .platform.app.yaml
**Updates** 
* `dependencies:php:wp-cli/wp-cli` to `wp-cli/wp-cli-bundle`
* `web:locations:"wp/wp-content/uploads":root` from "web/wp/wp-content/uploads" to "web/app/uploads"
* mount from "web/app/wp-content/uploads" to "web/app/uploads":
=> Fixes issues 11, 12, 13 in bedrock template

.github/workflows/updates.yaml, .gitignore
Adds `REPOOWNER` and `TEMPLATEOWNER` env vars to track github namespaces for repos
Re-orders steps in build (+adds step numbers to names):
- pre-start = all configuration steps for python and poetry, default env vars for passing data between steps
- 1 make sure the template repo exists
- 2 `(new)` verify auto-merge for repo is enabled, if not, enable
- 3 Get repo's default branch name
- 4 `(new)` Add branch protection rule to default branch
- 5 `(new)` Patch branch protection rule to remove review requirement
- 6 Check if update branch already exists
- 7 doit cleanup
- 8 doit initialize template build
- 9 doit initialize remote
- 10 doit update
- 11 doit platformify
- 12 doit branch template
- 13 Push template
- 14 check if updates were pushed to update branch. If not, it's assumed there …
=> Updates per conversation in 1-on-1 meeting

templates/gatsby-wordpress/files/wordpress/.platform.app.yaml, templates/wordpress-vanilla/files/.platform.app.yaml
=> removes `wp-cli/wp-cli` as a php dependency in .platform.app.yaml

templates/wordpress-bedrock/files/.environment, templates/wordpress-bedrock/files/README.md
in the [.environment file](https://github.com/platformsh-templates/wordpress-bedrock/blob/master/.environment), it's setting the [constant WP_ENV to development if the current branch isn't master](https://github.com/platformsh-templates/wordpress-bedrock/blob/master/.environment#L10). However, most have changed their default/production away from that term to something else which means every branch has WP_ENV set to development.
In addition, now that we have PLATFORM_ENVIRONMENT_TYPE with values of production|development|staging we should be able to change the codeblock in question to just
This will close #48 @ https://github.com/platformsh-templates/wordpress-bedrock/issues/48
=> Update wordpress-bedrock .environment file

templates/wordpress-bedrock/files/.platform.app.yaml, templates/wordpress-composer/files/.platform.app.yaml, templates/wordpress-vanilla/files/.platform.app.yaml, templates/wordpress-woocommerce/files/.platform.app.yaml
adds `allow: false` to `wp-content/uploads` and then an override rule with `allow: true` against a whitelist of file extensions
Whitelist:
`(?<!\-lock)\.(?i:jpe?g|gif|png|svg|bmp|ico|css|js(?:on)?|eot|ttf|woff|woff2|pdf|docx?|xlsx?|pp[st]x?|psd|odt|key|mp[2-5g]|m4[av]|og[gv]|wav|mov|wm[av]|avi|3g[p2])$`
For those file extensions, adds a cache expires of 1w
[Closes issue 75 in WordPress Bedrock template.](https://github.com/platformsh-templates/wordpress-bedrock/issues/75)
=> whitelist serveable file

common/sourceop-auto-update/.github/workflows/autopr.yaml, common/sourceop-auto-update/.github/workflows/sourceops.yaml, common/sourceop-auto-update/.github/workflows/testprenvironment.yaml, project/__init__.py
Adds github workflow files to `common/sourceop-auto-update/` for performing scheduled source operations, auto PRs, a smoke test. 
Adds a check for `source:operations:auto-update` in the templates `.platform.app.yaml` file, and if present, copies the contents from `common/sourceop-auto-update` into the template's build directory.
Closes #661
=> Feat/661 sourceop GitHub workflow

templates/drupal10/platformsh.wizard.yaml
Closes #751 
Updates the installation instructions for the Platform.sh CLI in the wizard file for the Drupal10 template
=> Updates the instructions for the Platform.sh CLI installer

project/wordpress.py, templates/wordpress-bedrock/files/README.md
changes the order of commands so that the deletion of the .github + .circleci directories from the *upstream* occurs before we add in our .github directory
updates readme for wordpress-bedrock from php7.4 --> php8.1 (this was changed in the template directly, but then wiped out from the template-builder)
Closes #765
=> order of platformify cmds in WP Bedrock

project-issues.yaml
Adds issues to template-builder project when opened https://github.com/marketplace/actions/add-to-github-projects
=> Add issues-to-project action

templates/drupal10/files/.platform.app.yaml
It's awkward to call scripts like this inside templates, as customers may have copied the files without copying the permissions.
=> drupal10: don't require script to be executable

common/sourceop-auto-update/.github/workflows/autopr.yaml, common/sourceop-auto-update/.github/workflows/last-updated.yaml, common/sourceop-auto-update/.github/workflows/sourceops.yaml, common/sourceop-auto-update/.github/workflows/testprenvironment.yaml
Closes #829 
As our automatic maintenance of templates has progressed, so has the amount of logic contained in the individual github workflow files. To prevent us from having to make large scale updates to the github workflow files across all template repositories in the future, this update changes all workflows to use a collection of [reusable workflows](https://github.com/platformsh-templates/ghrw-templates) so we can make most changes there and have it affect all individual template repositories at once.
=> Use reusable workflows

templates/typo3-v11/.platform.template.yaml
The current version of the template points to the Typo3-v11 repo using the `git` protocol. This causes an error when Platform.sh tries to clone the repository. Changing it to `https` resolves this.
=> Fix git repository route protocol

common/all/.github/workflows/project-issues.yaml
adds project-issues sync workflow to common/all/.github/workflows to have each individual template repository's issues to the template builder project
Closes #838 
@chadwcarlson I wasn't sure if you wanted this workflow to be added to **every** template (ie `common/all/.github/workflows`) or only those templates where we've added the source-operations workflows. This PR has it placed in  `all` but I can move it if you want.
=> [Enhancement] adds project issues sync workflow

templates/drupal9-multisite/.platform.template.yaml, templates/eleventy-strapi/.platform.template.yaml, templates/gatsby-drupal/.platform.template.yaml, templates/gatsby-wordpress/.platform.template.yaml, templates/hugo/.platform.template.yaml, templates/nextjs-drupal/.platform.template.yaml, templates/nextjs-wordpress/.platform.template.yaml
adds `info:class: demo` property to .platform.template.yaml for the following templates:
- drupal9-multisite
- eleventy-strapi
- gatsby-drupal
- gatsby-wordpress
- hugo
- nextjs-drupal
- nextjs-wordpress
Associated with #842
=> adds `info:class: demo` property to the following templates

project/drupal.py, project/remote.py, project/sylius.py, project/wordpress.py
Closes #881 
Previously, individual template classes were manually removing the `.github` directory, along with other CI-related services (e.g. `.circleci`, `.tugboat`, etc.). However, that meant _our_ `.github` directory was also being removed. 
This PR attempts to resolve this issue of theirs vs our `.github` directory:
1. after cloning our template repository, checks for the existence of a `.github` directory, and if present, renames to `tmp.github`
2. after pulling from the upstream, if a `.github` directory is reintroduced, deletes it
3. then if our `tmp.github` directory exists, renames it back to `.github`
This occurs during the `update` action, _before_ the `platformify` action which allows us to preserve the `all/common/.github` and `all/sourceop-auto-update/.github` contents as …
=> [TB clean-up] Resolve ours vs theirs .github directory

project/remote.py
previous update chained our .github deletion and moves with &&s but if an upstream _didn't_ introduce a `.github` directory the command would fail since the test failed. 
Reformats the command to only attempt a delete if the test passes.
=> only attempts to delete if the directory is there

templates/strapi4/platformsh.wizard.yaml
incorrect indentation in strapi4's wizard file was causing it to display incorrectly in platform.sh console.
=> corrects indentation in yaml properties
